[[imports]]
path = "github.com/jungvonmatt/karate-kit/core"

[[imports.mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/jungvonmatt/karate-kit/ui"

[[imports.mounts]]
source = "assets"
target = "assets"

[[imports.mounts]]
source = "layouts"
target = "layouts"

[[imports.mounts]]
source = "content"
target = "content/storybook"

[[imports.mounts]]
source = "data"
target = "data/storybook"
