contentDir = "content/storybook"
ignoreFiles = []
disableKinds = [
  "taxonomy",
  "term",
  "RSS",
  "sitemap",
  "robotsTXT",
  "404"
]
titleCaseStyle = "Go"
theme = [
  "github.com/jungvonmatt/karate-kit/ui",
  "github.com/jungvonmatt/karate-kit/core",
]

# Only render default language (en)
disableLanguages = ['de','en']
languageCode = "sk"
defaultContentLanguage = "sk"
defaultContentLanguageInSubdir = false

[languages]
  [languages.sk]
  contentDir = "content/storybook"

[minify.tdewolff.html]
keepQuotes = true
keepWhitespace = true

[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
  [mediaTypes."text/x-markdown"]
  suffixes = ["stories.mdx"]
  [mediaTypes."application/javascript"]
  suffixes = ["stories.js"]

[outputFormats]
  [outputFormats.MDX]
  mediaType = "text/x-markdown"
  baseName = "docs"
  [outputFormats.JS]
  mediaType = "application/javascript"
  baseName = "canvas"

[outputs]
page = ["JS"]
section = ["MDX"]
